namespace EvilHashConvertor
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lstNames = new System.Windows.Forms.ListBox();
            this.txtResult = new System.Windows.Forms.RichTextBox();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // lstNames
            // 
            this.lstNames.FormattingEnabled = true;
            this.lstNames.Items.AddRange(new object[] {
            "EVENT_BUILD_AREA_BLOCKED",
            "EVENT_MINION_ASSIGNED_ROOMBUILD",
            "EVENT_MINION_UNASSIGNED_ROOMBUILD",
            "EVENT_ROOM_NOT_SAFE_TO_DELETE",
            "EVENT_DESERTION",
            "EVENT_MOVE_OBJECT_COMPLETED",
            "EVENT_TORTURE_CANCELLED",
            "EVENT_TORTURE_BEGIN",
            "EVENT_TORTURER_BEGIN",
            "EVENT_TORTURE_SUCCEEDED",
            "EVENT_TORTURE_FAILED",
            "EVENT_CHARACTER_LEAVING_COMBAT",
            "EVENT_AGENT_DAMAGED_HEALTH",
            "EVENT_AGENT_DAMAGED_LOYALTY",
            "EVENT_AGENT_DAMAGED_SMARTS",
            "EVENT_AGENT_DAMAGED_ATTENTION",
            "EVENT_AGENT_DAMAGED_ENDURANCE",
            "EVENT_AGENTGROUP_BECOMING_INVALID",
            "EVENT_AGENTGROUP_BECOMING_VALID",
            "EVENT_AGENTGROUP_ANGRY",
            "EVENT_OBJECT_BEING_STOLEN",
            "EVENT_OBJECT_BEING_INVESTIGATED",
            "EVENT_ROOM_BUILDING_CANCELLED",
            "EVENT_ROOM_BUILDING_PAUSED",
            "EVENT_ROOM_BUILDING_UNPAUSED",
            "EVENT_ROOM_BUILDING_DELAYED_BY_OBJECT",
            "EVENT_ROOM_BUILDING_ORDERED",
            "EVENT_ROOM_BUILDING_VALID_NOW",
            "EVENT_ROOM_BUILDING_START_DELAYED_BY_OBJECT",
            "EVENT_ROOM_BUILDING_QUEUED",
            "EVENT_SETONFIRE",
            "EVENT_TAG_IGNORE",
            "EVENT_TAG_KILL",
            "EVENT_TAG_CAPTURE",
            "EVENT_TAG_WEAKEN",
            "EVENT_CHARACTER_INGAME",
            "EVENT_CHARACTER_OUTOFGAME",
            "EVENT_INCAPACITATED_HEALTH",
            "EVENT_INCAPACITATED_LOYALTY",
            "EVENT_INCAPACITATED_SMARTS",
            "EVENT_INCAPACITATED_ATTENTION",
            "EVENT_INCAPACITATED_ENDURANCE",
            "EVENT_CHARACTER_BECOMING_INVALID",
            "EVENT_CHARACTER_BECOMING_VALID",
            "EVENT_CHARACTER_KILLED",
            "EVENT_CHARACTER_DIED_IN_PRISON",
            "EVENT_ATTACK",
            "EVENT_ATTACKGENIUS",
            "EVENT_GENIUS_TARGETTED",
            "EVENT_SECURITY_BREACH",
            "EVENT_GENIUS_DEAD",
            "EVENT_GENIUS_GLOATING",
            "EVENT_HENCHMANABILITY_SUPERHEADSHOT",
            "EVENT_HENCHMAN_USED_SUPERHEADSHOT",
            "EVENT_HENCHMANABILITY_MEDITATE",
            "EVENT_HENCHMAN_USED_MEDITATE",
            "EVENT_HENCHMANABILITY_ROAR",
            "EVENT_HENCHMAN_USED_ROAR",
            "EVENT_HENCHMANABILITY_WORKETHIC",
            "EVENT_HENCHMAN_USED_WORKETHIC",
            "EVENT_HENCHMANABILITY_DEDUCTION",
            "EVENT_HENCHMAN_USED_DEDUCTION",
            "EVENT_HENCHMANABILITY_GATHERRETINUE",
            "EVENT_HENCHMAN_USED_GATHERRETINUE",
            "EVENT_HENCHMANABILITY_GRENADEJIG",
            "EVENT_HENCHMAN_USED_GRENADEJIG",
            "EVENT_HENCHMANABILITY_MONKEYPOUND",
            "EVENT_HENCHMAN_USED_MONKEYPOUND",
            "EVENT_HENCHMANABILITY_ELECTROSHOCK",
            "EVENT_HENCHMAN_USED_ELECTROSHOCK",
            "EVENT_HENCHMANABILITY_MINEFIELD",
            "EVENT_HENCHMAN_USED_MINEFIELD",
            "EVENT_HENCHMANABILITY_WINDWALK",
            "EVENT_HENCHMAN_USED_WINDWALK",
            "EVENT_HENCHMANABILITY_VOODOOPUPPETRY",
            "EVENT_HENCHMAN_USED_VOODOOPUPPETRY",
            "EVENT_HENCHMANABILITY_EVISCERATE",
            "EVENT_HENCHMAN_USED_EVISCERATE",
            "EVENT_HENCHMANABILITY_GHETTOPOSSE",
            "EVENT_HENCHMAN_USED_GHETTOPOSSE",
            "EVENT_HENCHMANABILITY_VOODOOMINDFOG",
            "EVENT_HENCHMAN_USED_VOODOOMINDFOG",
            "EVENT_HENCHMANABILITY_PSYCHICTERROR",
            "EVENT_HENCHMAN_USED_PSYCHICTERROR",
            "EVENT_HENCHMANABILITY_SMOOTHOPERATOR",
            "EVENT_HENCHMAN_USED_SMOOTHOPERATOR",
            "EVENT_HENCHMANABILITY_TELEPATHICMINDCONTROL",
            "EVENT_HENCHMAN_USED_TELEPATHICMINDCONTROL",
            "EVENT_HENCHMANABILITY_WILLPOWERDRAIN",
            "EVENT_HENCHMAN_USED_WILLPOWERDRAIN",
            "EVENT_HENCHMANABILITY_FACADEOFNORMALITY",
            "EVENT_HENCHMAN_USED_FACADEOFNORMALITY",
            "EVENT_HENCHMANABILITY_POISONPOURHOMME",
            "EVENT_HENCHMAN_USED_POISONPOURHOMME",
            "EVENT_HENCHMANABILITY_HALLUCINOGENICPOWDER",
            "EVENT_HENCHMAN_USED_HALLUCINOGENICPOWDER",
            "EVENT_HENCHMANABILITY_MOTHERLYLOVE",
            "EVENT_HENCHMAN_USED_MOTHERLYLOVE",
            "EVENT_HENCHMANABILITY_TERRORTACTICS",
            "EVENT_HENCHMAN_USED_TERRORTACTICS",
            "EVENT_HENCHMANABILITY_MANTRAPS",
            "EVENT_HENCHMAN_USED_MANTRAPS",
            "EVENT_HENCHMANABILITY_PENDRAGON",
            "EVENT_HENCHMAN_USED_PENDRAGON",
            "EVENT_HENCHMAN_SPECIALABILITYAVAILABLE",
            "EVENT_HENCHMAN_ATTACK_ORDERED",
            "EVENT_HENCHMAN_DIED",
            "EVENT_CHARACTER_IMPRISONED",
            "EVENT_SCENERY_BECOMING_INVALID",
            "EVENT_SCENERY_BECOMING_VALID",
            "EVENT_OBJECT_STOLEN",
            "EVENT_NOTORIETY_CHANGE",
            "EVENT_HEAT_CHANGE",
            "EVENT_OBJECT_DESTROYED",
            "EVENT_TRAINING_BEGINS",
            "EVENT_TRAINING_ENDS",
            "EVENT_TORTURE_BEGINS",
            "EVENT_TORTURE_ENDS",
            "EVENT_INTERACTION_BEGINS",
            "EVENT_INTERACTION_ENDS",
            "EVENT_ASSIGNCREW",
            "EVENT_OBJECT_BECOMING_INVALID",
            "EVENT_OBJECT_BECOMING_VALID",
            "EVENT_INTERROGATION_OBJECT_BECOMING_VALID",
            "EVENT_UI_ORDER_RESEARCH",
            "EVENT_RESEARCH_STARTED",
            "EVENT_RESEARCH_CRITICALFAILURE_CANCELLED",
            "EVENT_RESEARCH_CRITICALFAILURE_OCCURRED",
            "EVENT_ROOM_DEMOLITION_ORDERED",
            "EVENT_SECURITYCAMERATRIGGERED",
            "EVENT_SCENERY_BECOMING_INVALID",
            "EVENT_SCENERY_BECOMING_VALID",
            "EVENT_INDOOR_STRONGROOM_BUILT",
            "EVENT_ENTITY_ADDED_TO_GAME",
            "EVENT_ENTITY_REMOVED_FROM_GAME",
            "EVENT_CHARACTER_LEAVING_ISLAND",
            "EVENT_CHARACTER_LEAVING_ISLAND",
            "EVENT_CHARACTER_ABOUT_TO_LEAVE_ISLAND",
            "EVENT_MISSION_BEGUN",
            "EVENT_MISSION_ENDED",
            "EVENT_MISSION_SUCCEEDED",
            "EVENT_MISSION_ABORTED",
            "EVENT_MISSION_FAILED",
            "EVENT_NO_PLACE_FOR_OBJECT",
            "EVENT_HENCHMAN_RETURNED",
            "EVENT_OBJECTIVE_AVAILABLE",
            "EVENT_OBJECTIVE_COMPLETED",
            "EVENT_PRIMARY_OBJECTIVE_COMPLETED",
            "EVENT_SECONDARY_OBJECTIVE_COMPLETED",
            "EVENT_OUT_OF_MONEY",
            "EVENT_MONEY_UNDELIVERABLE",
            "EVENT_NEW_OBJECTS",
            "EVENT_NEW_ROOMS",
            "EVENT_RECRUITMENT_RATE_CHANGED",
            "EVENT_MINIONS_OVER_ORDERED",
            "EVENT_ALERT_GREEN",
            "EVENT_ALERT_AMBER",
            "EVENT_ALERT_RE",
            "EVENT_OUT_OF_MONEY_RECRUITMENT",
            "EVENT_POWER_RESTORED",
            "EVENT_POWER_EMERGENCY",
            "EVENT_POWER_NOPOWER",
            "EVENT_POWER_LOW_POWER",
            "EVENT_RESEARCH_FAILED",
            "EVENT_RESEARCH_SUCCEEDED",
            "EVENT_COMPLETED_SECURITY_NETWORK",
            "EVENT_TORTURE_ORDERED",
            "EVENT_OBJECT_MOVED",
            "EVENT_OBJECT_MOVED_SUCCESS",
            "EVENT_OP_EXISTING_OBJECT_BLOCKED",
            "EVENT_OP_ALL_CRITICAL_HOTSPOTS_BLOCKED",
            "EVENT_OP_SOME_HOTSPOTS_BLOCKED",
            "EVENT_BEGINGAME",
            "EVENT_MOVE_COMMAND_ISSUED",
            "EVENT_ENTITY_SELECTED",
            "EVENT_ALL_ENTITIES_DESELECTED",
            "EVENT_PREVIEW_OBJECT_ROTATED",
            "EVENT_CLICKED_ON_MINIMAP",
            "EVENT_MB_YES",
            "EVENT_MB_NO",
            "EVENT_MB_CANCEL",
            "EVENT_GLOSSARY_ENTITY_%05d",
            "EVENT_UI_EXPANDED_OBJECTIVE",
            "EVENT_RESEARCH_LOSECASHINCENTIVES",
            "EVENT_ROOM_BUILD_TOO_NARROW",
            "EVENT_ROOM_BUILD_SPLIT",
            "EVENT_ROOM_BUILD_NO_ENTRANCE",
            "EVENT_UI_VIEW_AGENT_STATS",
            "EVENT_UI_ORDER_OBJECTMOVE",
            "EVENT_UI_ORDER_OBJECTDELETE",
            "EVENT_PRISONER_RELEASE_ORDERED",
            "EVENT_PRISONER_KILL_ORDERED",
            "EVENT_PRISONER_INTERROGATE_ORDERED",
            "EVENT_UI_ORDER_OBJECTDELETE",
            "EVENT_BUILDROOM_DIALOG",
            "EVENT_UI_ORDER_BUILDROOM",
            "EVENT_STATSMINION",
            "EVENT_STATSHENCHMAN",
            "EVENT_STATSAGENT",
            "EVENT_STATSTOURIST",
            "EVENT_STATSOBJECT",
            "EVENT_STATSITEM",
            "EVENT_OBJECT_PLACED",
            "EVENT_OP_SUCCESS",
            "EVENT_OP_NO_WORKERS",
            "EVENT_COMPLETED_TRAP_NETWORK",
            "EVENT_LINKMODE",
            "EVENT_COMPONENTS_LINKED",
            "EVENT_MINIONMANAGEMENT",
            "EVENT_RESEARCH_DIALOG",
            "EVENT_WORLDMAP",
            "EVENT_CAMERA_ROTATED",
            "EVENT_CAMERA_MOVED",
            "EVENT_CAMERA_ZOOMED",
            "EVENT_ATTACK",
            "EVENT_BUILDOBJECTS",
            "EVENT_CHARACTER_BECOMING_VALID",
            "EVENT_OBJECT_BECOMING_VALID",
            "EVENT_OBJECTIVE_COMPLETED",
            "EVENT_RESEARCH_GETTIKICAMERA",
            "EVENT_RESEARCH_GETBIGSCREEN",
            "EVENT_RESEARCH_GETCHARGECANNON",
            "EVENT_RESEARCH_GETSATAN",
            "EVENT_RESEARCH_GETWINDTRAP",
            "EVENT_RESEARCH_GETPOISONHOOD",
            "EVENT_RESEARCH_GETXRAY",
            "EVENT_RESEARCH_GETLASERBEAM",
            "EVENT_RESEARCH_GETHEAVYDOOR",
            "EVENT_RESEARCH_GETSMARTBEES",
            "EVENT_NOTORIETY_CHANGE",
            "EVENT_MISSION_SUCCEEDED",
            "EVENT_INCAPACITATED_SMARTS",
            "EVENT_INCAPACITATED_LOYALTY",
            "EVENT_INCAPACITATED_ATTENTION",
            "EVENT_INCAPACITATED_ENDURANCE",
            "EVENT_CHARACTER_BECOMING_INVALID",
            "EVENT_RESEARCH_GETEVILSAT",
            "EVENT_STATSAGENT",
            "EVENT_SCENERY_BECOMING_VALID",
            "EVENT_UI_VIEW_AGENT_STATS",
            "EVENT_MB_YES",
            "EVENT_MB_NO",
            "EVENT_MB_CANCEL",
            "EVENT_GENIUS_DEAD",
            "EVENT_STATSOBJECT",
            "EVENT_TORTURE_BEGIN",
            "EVENT_PIE_END",
            "EVENT_CHARACTER_LEAVING_ISLAND",
            "EVENT_CHARACTER_LEAVING_COMBAT",
            "EVENT_AGENTGROUP_ANGRY",
            "EVENT_INCAPACITATED_HEALTH",
            "EVENT_ENTITY_ADDED_TO_GAME",
            "EVENT_ENTITY_REMOVED_FROM_GAME",
            "EVENT_OBJECT_STOLEN",
            "EVENT_STATSMINION",
            "EVENT_OBJECT_PLACED",
            "EVENT_ROOM_BUILDING_UNPAUSED",
            "EVENT_ROOM_BUILDING_PAUSED",
            "EVENT_CHARACTER_FINISHING_COMBAT",
            "EVENT_CAMERA_ROTATED",
            "EVENT_CAMERA_MOVED",
            "EVENT_CAMERA_ZOOMED",
            "EVENT_MOVE_OBJECT_COMPLETED",
            "EVENT_COMPONENTS_LINKED",
            "EVENT_MISSION_ENDED",
            "EVENT_HENCHMANABILITY_GATHERRETINUE",
            "EVENT_HENCHMAN_USED_GATHERRETINUE",
            "EVENT_TORTURE_ORDERED",
            "EVENT_TRAINING_BEGINS",
            "EVENT_UI_ORDER_MISSION",
            "EVENT_MISSION_BEGUN",
            "EVENT_CHARACTER_INGAME",
            "EVENT_CHARACTER_OUTOFGAME",
            "EVENT_OBJECT_BECOMING_INVALID",
            "EVENT_MINIGAME_SQUAD_COMITTED",
            "EVENT_MINIGAME_SQUAD_ADDED",
            "EVENT_MINIGAME_SQUAD_REMOVED",
            "EVENT_SETONFIRE",
            "EVENT_PREVIEW_OBJECT_ROTATED",
            "EVENT_MOVE_COMMAND_ISSUED",
            "EVENT_TORTURE_ENDS",
            "EVENT_POWER_NOPOWER",
            "EVENT_ROOM_BUILDING_ORDERED",
            "EVENT_RESEARCH_STARTED",
            "EVENT_MISSION_FAILED",
            "EVENT_MISSION_CANCELLED",
            "EVENT_MISSION_ABORTED",
            "EVENT_OBJECTIVE6_EXITCODEXATN",
            "EVENT_RESEARCH_CODEX_AI",
            "EVENT_RESEARCH_CODEX_GREENHOUSE",
            "EVENT_RESEARCH_CODEX_ENVCHAMBER",
            "EVENT_HINT_FREEZER",
            "EVENT_HINT_INTERROGATION",
            "EVENT_HINT_POWER",
            "EVENT_HINT_TRAINING",
            "EVENT_HINT_MINIONSTATS",
            "EVENT_OBJECT_BEING_STOLEN",
            "EVENT_RESEARCH_O8_USA1",
            "EVENT_RESEARCH_O8_USA2",
            "EVENT_RESEARCH_O8_USA3",
            "EVENT_AGENT_DAMAGED_HEALTH",
            "EVENT_AGENT_DAMAGED_SMARTS",
            "EVENT_AGENT_DAMAGED_LOYALTY",
            "EVENT_AGENT_DAMAGED_ATTENTION",
            "EVENT_AGENT_DAMAGED_ENDURANCE",
            "EVENT_RESEARCH_O8_CHINA3",
            "EVENT_RESEARCH_O8_CHINA2",
            "EVENT_RESEARCH_O8_CHINA1",
            "EVENT_RESEARCH_O8_EUROPE3",
            "EVENT_RESEARCH_O8_EUROPE2",
            "EVENT_RESEARCH_O8_EUROPE1",
            "EVENT_O8_TORTUREATT",
            "EVENT_O8_TORTURESMARTS",
            "EVENT_O8_TORTUREHEALTH",
            "EVENT_POWER_RESTORED",
            "EVENT_CHARACTER_IMPRISONED",
            "EVENT_ENTITY_SELECTED",
            "EVENT_HINT_CONSTRUCTION_WORKER",
            "EVENT_HINT_HENCHMAN_BASIC",
            "EVENT_HINT_EVIL_AVATAR",
            "EVENT_HINT_ROOM_STAFFING",
            "EVENT_HINT_SECURITY_DOORS",
            "EVENT_HINT_TAGGING_CHARACTERS",
            "EVENT_HINT_AGENTS",
            "EVENT_HINT_NOTORIETY",
            "EVENT_HINT_PRISONERS",
            "EVENT_HINT_INTERROGATION_MISSION",
            "EVENT_HINT_VALET",
            "EVENT_HINT_GUARD",
            "EVENT_HINT_TECHNICIAN",
            "EVENT_HINT_SURVEILLANCE",
            "EVENT_HINT_TRAPS",
            "EVENT_HINT_GLOBAL_ALERTS",
            "EVENT_HINT_GUN_RACKS",
            "EVENT_HINT_RESEARCH",
            "EVENT_HINT_TOURISTS",
            "EVENT_SECURITY_BREACH",
            "EVENT_HEAT_CHANGE",
            "EVENT_ALERT_GREEN",
            "EVENT_ALERT_AMBER",
            "EVENT_ALERT_RED",
            "EVENT_O9_NOTENOUGHAERIALS",
            "EVENT_INTERROGATION_OBJECT_BECOMING_VALID",
            "EVENT_RESEARCH_GETBIOTANKS",
            "EVENT_RESEARCH_GETIMPACT",
            "EVENT_RESEARCH_GETLASER",
            "EVENT_RESEARCH_GETCENTRIFUGE",
            "EVENT_RESEARCH_GETPROMETHEUS",
            "EVENT_RESEARCH_GETDREADMILL",
            "EVENT_RESEARCH_GETGOLDENHANCER",
            "EVENT_RESEARCH_GETCOMMARRAY",
            "EVENT_RESEARCH_GETFLAMETHROWER",
            "EVENT_RESEARCH_GETSTOCKEXCHANGE",
            "EVENT_RESEARCH_GETARTWATCHDOG",
            "EVENT_RESEARCH_GETRADIOALERTSTATION",
            "EVENT_RESEARCH_GETVENUSMANTRAP",
            "EVENT_RESEARCH_GETBRAINIAC",
            "EVENT_RESEARCH_GETMULTIGYM",
            "EVENT_RESEARCH_GETARCADECABINET",
            "EVENT_RESEARCH_GETDEATHCUBICLE",
            "EVENT_RESEARCH_GETZOOMCAMERA",
            "EVENT_RESEARCH_GETGASHOODLOYALTY",
            "EVENT_RESEARCH_GETPITPUNISHER",
            "EVENT_RESEARCH_GETSENTRYGUN",
            "EVENT_RESEARCH_GETBOOKCASE",
            "EVENT_RESEARCH_GETDISGUISEDGEN",
            "EVENT_RESEARCH_GETDISGUISEDDOOR",
            "EVENT_RESEARCH_GETLASERTRIP",
            "EVENT_RESEARCH_GETLEARNINGCHANNEL",
            "EVENT_RESEARCH_GETSALADBAR",
            "EVENT_RESEARCH_GETWIDESCREENTV",
            "EVENT_RESEARCH_GETXRAYCHAMBER",
            "EVENT_RESEARCH_GETHEAVYTANNOY",
            "EVENT_RESEARCH_GETFIELDBARRIER",
            "EVENT_RESEARCH_GETDISGUISEDWEAPRACK",
            "EVENT_RESEARCH_GETDISGUISEDCELL",
            "EVENT_RESEARCH_GETDONOTPRESS",
            "EVENT_RESEARCH_GASHOODSMARTS",
            "EVENT_RESEARCH_GETSTORAGERACK",
            "EVENT_RESEARCH_GETCONTROLTSTATION",
            "EVENT_RESEARCH_GETNUCLEARPOWER",
            "EVENT_RESEARCH_GETMOTIONTRACKER",
            "EVENT_RESEARCH_GETHDCAPACITOR",
            "EVENT_RESEARCH_GETDISGUISEDCAMERA",
            "EVENT_RESEARCH_GETDISGUISEDSENTRYGUN",
            "EVENT_RESEARCH_GETBEES",
            "EVENT_RESEARCH_GETSENSORDOOR",
            "EVENT_RESEARCH_GETGASHOODENDURANCE",
            "EVENT_RESEARCH_GETGASHOODATTENTION",
            "EVENT_RESEARCH_GETRECLININGCHAIR",
            "EVENT_RESEARCH_GETINFIRMARYCHAIR",
            "EVENT_RESEARCH_GETSAWBLADES",
            "EVENT_RESEARCH_GETPALMTREETRAP",
            "EVENT_RESEARCH_GETBRAINWASHER",
            "EVENT_RESEARCH_GETMISDIRECTION",
            "EVENT_RESEARCH_GETMONEYMADNESS",
            "EVENT_RESEARCH_GETCRYOCHAMBER",
            "EVENT_RESEARCH_GETAUTOSURGEON",
            "EVENT_RESEARCH_GETDAMNEDDAMSEL",
            "EVENT_RESEARCH_GETPIRAHNATANK",
            "EVENT_RESEARCH_GETSUCKER",
            "EVENT_RESEARCH_GETAUTOCHEF",
            "EVENT_RESEARCH_GETMONKEYINNABOX",
            "EVENT_ROOM_BUILD_NO_ENTRANCE",
            "EVENT_ROOM_BUILD_SPLIT",
            "EVENT_ROOM_BUILD_TOO_NARROW",
            "EVENT_WORLDMAP",
            "EVENT_UI_EXPANDED_OBJECTIVE",
            "EVENT_RESEARCH_GETPINBALL",
            "EVENT_SUPERAGENT_SMASH_UNLOCK",
            "EVENT_SUPERAGENT_ANVIL_UNLOCK",
            "EVENT_SUPERAGENT_SABRE_UNLOCK",
            "EVENT_SUPERAGENT_HAMMER_UNLOCK",
            "EVENT_SUPERAGENT_PATRIOT_UNLOCK",
            "EVENT_SUPERAGENT_SMASH_DEFEAT",
            "EVENT_SUPERAGENT_ANVIL_DEFEAT",
            "EVENT_SUPERAGENT_HAMMER_DEFEAT",
            "EVENT_SUPERAGENT_PATRIOT_DEFEAT",
            "EVENT_SUPERAGENT_SABRE_DEFEAT",
            "EVENT_RESEARCH_TOWEL",
            "EVENT_GENERIC_LOOT_STOLEN",
            "EVENT_HINT_WORLDDOMINATION",
            "EVENT_OBJECTIVE16_ACCOUNTANT1",
            "EVENT_OBJECTIVE16_ACCOUNTANT2",
            "EVENT_OBJECTIVE16_ACCOUNTANT3",
            "EVENT_OBJECTIVE16_ACCOUNTANT4",
            "EVENT_OBJECTIVE16_ACCOUNTANT5",
            "EVENT_OBJECTIVE16_ACCOUNTANT6",
            "EVENT_OBJECTIVE16_ACCOUNTANT7",
            "EVENT_OBJECTIVE16_ACCOUNTANT8",
            "EVENT_CHARACTER_ABOUT_TO_LEAVE_ISLAND",
            "EVENT_CHARACTER_KILLED",
            "EVENT_OBJECTIVE15_MINIONARRIVED",
            "EVENT_O9_BROADCASTSTARTED",
            "EVENT_ALL_ENTITIES_DESELECTED",
            "EVENT_HENCHMAN_ATTACK_ORDERED",
            "EVENT_OP_SOME_HOTSPOTS_BLOCKED",
            "EVENT_OP_ALL_CRITICAL_HOTSPOTS_BLOCKED",
            "EVENT_OP_EXISTING_OBJECT_BLOCKED",
            "EVENT_OBJECT_MOVED_SUCCESS",
            "EVENT_RECRUITMENT_RATE_CHANGED",
            "EVENT_OP_SUCCESS",
            "EVENT_PLAYTHING_AWARDED",
            "EVENT_PLAYTHING_DEAD",
            "EVENT_NEWHINT_TUNNELING",
            "EVENT_NEWHINT_GAMEHELP",
            "EVENT_NEWHINT_CHARSTATS",
            "EVENT_NEWHINT_WORLDMAP_CASH",
            "EVENT_NEWHINT_TRAINING",
            "EVENT_NEWHINT_WORLDMAP_AOI",
            "EVENT_NEWHINT_RESEARCH",
            "EVENT_NEWHINT_SUPERAGENT",
            "EVENT_NEWHINT_BUILDING",
            "EVENT_NEWHINT_RECRUITING",
            "EVENT_NEWHINT_TAGS",
            "EVENT_NEWHINT_CASH",
            "EVENT_NEWHINT_INTERRORGATION",
            "EVENT_NEWHINT_TRAINING2",
            "EVENT_NEWHINT_MOVE_STRONGROOM",
            "EVENT_NEWHINT_DOORS",
            "EVENT_NEWHINT_AOI_NOTORIETY",
            "EVENT_NEWHINT_TRAPS",
            "EVENT_NEWHINT_SECURITY",
            "EVENT_NEWHINT_POWER",
            "EVENT_NEWHINT_MOVEISLAND",
            "EVENT_NEWHINT_HENCHMAN",
            "EVENT_NEWHINT_AGENTS",
            "EVENT_NEWHINT_RECOVERY",
            "EVENT_NEWHINT_MAIN_INTERFACE",
            "EVENT_NEWHINT_WORLDMAP_DANGER",
            "EVENT_TRIGGER_HINTVIDEO",
            "EVENT_CHARACTER_DIED_IN_PRISON",
            "EVENT_INDOOR_STRONGROOM_BUILT",
            "EVENT_NEWHINT_INTERRORGATION_2",
            "EVENT_NEWHINT_RESEARCH2",
            "EVENT_COMPLETED_TRAP_NETWORK",
            "EVENT_COMPLETED_SECURITY_NETWORK",
            "EVENT_POWER_LOW_POWER",
            "EVENT_NEWHINT_LAYOUT",
            "EVENT_OBJECT_BEING_INVESTIGATED",
            "EVENT_CLICKED_ON_MINIMAP",
            "EVENT_NEWHINT_TRAINING3",
            "EVENT_HENCHMAN_SPECIALABILITYAVAILABLE",
            "EVENT_HENCHMAN_USED_SUPERHEADSHOT",
            "EVENT_HENCHMAN_USED_WINDWALK",
            "EVENT_HENCHMAN_USED_GHETTOPOSSE",
            "EVENT_HENCHMAN_USED_PSYCHICTERROR",
            "EVENT_HENCHMAN_USED_SMOOTHOPERATOR",
            "EVENT_HENCHMAN_USED_EVISCERATE",
            "EVENT_TORTURE_SUCCEEDED",
            "EVENT_TORTURE_FAILED",
            "EVENT_OBJECT_DESTROYED",
            "EVENT_GENIUS_GLOATING",
            "GUI_OBJECT_CONTEXT_MENU",
            "GUI_CHARACTER_CONTEXT_MENU",
            "GUI_ROOM_CONTEXT_MENU",
            "OBJECTIVE_7_GLOBALCHAOS_HINT"});
            this.lstNames.Location = new System.Drawing.Point(12, 12);
            this.lstNames.Name = "lstNames";
            this.lstNames.Size = new System.Drawing.Size(648, 238);
            this.lstNames.TabIndex = 0;
            // 
            // txtResult
            // 
            this.txtResult.Location = new System.Drawing.Point(13, 267);
            this.txtResult.Name = "txtResult";
            this.txtResult.Size = new System.Drawing.Size(647, 245);
            this.txtResult.TabIndex = 1;
            this.txtResult.Text = "";
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(585, 518);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 2;
            this.button1.Text = "button1";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(13, 518);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 3;
            this.button2.Text = "button2";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(672, 558);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.txtResult);
            this.Controls.Add(this.lstNames);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListBox lstNames;
        private System.Windows.Forms.RichTextBox txtResult;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
    }
}

